name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v1
        with:
          application-name: CloudPortfolioApp
          deployment-group: EC2Group
          deployment-config-name: CodeDeployDefault.AllAtOnce
          region: us-east-2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
