name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS CodeDeploy
        uses: aws-actions/aws-codedeploy-github-deploy@v1.0.8
        with:
          application-name: CloudPortfolioApp-713
          deployment-group: EC2Group-713
          deployment-description: "GitHub Actions Deployment"
          region: us-east-2
          github-token: ${{ secrets.GITHUB_TOKEN }}
          revision-location: github
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


