name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Zip source files
        run: |
          zip -r app.zip . -x "*.git*"

      - name: Upload to S3
        run: |
          aws s3 cp app.zip s3://sundin-portfoliobucket713/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name CloudPortfolioApp-713 \
            --deployment-group-name EC2Group-713 \
            --s3-location bucket=your-s3-bucket-name,key=app.zip,bundleType=zip \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --file-exists-behavior OVERWRITE
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
