name: Deploy to EC2 using CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS CodeDeploy
        uses: webfactory/create-aws-codedeploy-deployment@v0.3.1
        with:
          application-name: CloudPortfolioApp-713
          deployment-group: EC2Group-713
          deployment-description: "Deployed from GitHub Actions"
          region: us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

